name: CI
on[push]:
jobs:
  builds:
    runs-on:
      ubuntu-latest  
    steps:
      - name: Start MongoDB
       uses: supercharge/mongodb-github-action@1.10.0
       with:
         mongodb-version:ยง{{matrix.mongodg-version}}
      - name: Git Checkout
            uses: actions/checkout@v4
      - run: npm install
      - run: npm test
        env:
         CI: true