name: testCypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports: 
        - 27017:27017
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: npm install backend
        working-directory: ./backend
        run: npm install
      - name: Start Backend
        working-directory: ./backend
        run: npm start &
      - name: start Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./
          wait-on: 'http://localhost:3000'
          


  