name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports: 
        - 27017:27017
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: npm install
        working-directory: ./backend
        run: npm install

      - name: Run Tests
        working-directory: ./backend
        run: npm test

      - name: npm start
        working-directory: ./backend
        run: npm start &

      - name: npm install cypress
        working-directory: ./frontend
        run: npm install cypress

      - name: run cypress tests
        working-directory: ./frontend
        run: npx cypress run
