name: test

on:
  push:
    branches:
      - main
      - feature/abgabe-alex-p
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports: 
        - 27017:27017
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: npm install
        working-directory: ./backend
        run: npm install
      - name: Run Tests
        working-directory: ./backend
        run: npm test
      - name: npm install
        working-directory: ./frontend
        run: npm install
      - name: Start backend server
        run: |
          cd backend
          npm start &
        # env:
        #   MONGO_URL: mongodb://localhost:27017/testdb # Falls benötigt
      - name: Run Cypress tests
        run: |
          cd frontend
          npx cypress run